Repository AY2021S1-CS2103T-W16-3/tp, pull requests merged in 2020-11, with the labels that each got.

#268 Replace non-breaking spaces with regular spaces
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#267 Refactor editing of bookmark transactions
  docs/UserGuide.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmark/EditBookmarkExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmark/EditBookmarkIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ParserUtil.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/AddBookmarkExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/AddBookmarkIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/EditBookmarkExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/EditBookmarkIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/FinanceTracker.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/bookmark/BookmarkExpenseList.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/bookmark/BookmarkIncomeList.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/EditBookmarkExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/EditBookmarkIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ParserUtilTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/bookmark/BookmarkExpenseListTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/bookmark/BookmarkIncomeListTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#265 Modify search rules for find by title keyphrase
  docs/UserGuide.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/commons/util/StringUtil.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FindCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/TitleContainsKeyphrasesPredicate.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/TitleContainsKeywordsPredicate.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/commons/util/StringUtilTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindTransactionCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/stubs/FindCommandStub.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FindCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/TitleContainsKeyphrasesPredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/TitleContainsKeywordsPredicateTest.java
Labels: priority.high :1st_place_medal:, type.bug :bug:, type.documentation :roll_of_paper:

#266 Add clear command confirmation
  docs/UserGuide.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/MainApp.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ClearCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/Model.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManager.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/command/history/CommandHistory.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/CommandBox.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiManager.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ClearCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/stubs/ModelStub.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#273 Update PPP for Jingjing
  docs/team/zhaojj2209.md
Labels: priority.high :1st_place_medal:, type.documentation :roll_of_paper:

#275 Update PPP for Wei Liang
  docs/team/wltan.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#274 Update PPP for Siddarth
  docs/team/siddarth2824.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#276 Update PPP for Yong Ping
  docs/team/yongping827.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#277 Add PPP draft for Ian
  docs/images/ppp/ianyong/NoExternalSite.png
  docs/team/ianyong.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#272 Add tests for FinanceTrackerParser
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/BookmarkTransactionUtil.java
Labels: priority.medium :2nd_place_medal:, type.testing :rescue_worker_helmet:

#269 Modify base commands to throw exception on execute
  src/main/java/ay2021s1_cs2103_w16_3/finesse/commons/core/Messages.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListCommand.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/stubs/DeleteCommandStub.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/stubs/EditCommandStub.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/stubs/FindCommandStub.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/stubs/ModelStub.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
Labels: priority.medium :2nd_place_medal:, type.task :clipboard:

#281 Enforce no arguments for single-word commands
  docs/UserGuide.md
  docs/team/wltan.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/commons/core/Messages.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/AddBookmarkIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/ConvertBookmarkExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/ConvertBookmarkIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/DeleteBookmarkExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/DeleteBookmarkIncomeCommandParser.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#283 Add method in Date to return current date
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/ConvertBookmarkExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/ConvertBookmarkIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Date.java
Labels: priority.medium :2nd_place_medal:, type.task :clipboard:

#284 Repair broken abstraction - Amount
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/FinanceTracker.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlyBudget.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/ObservableAmount.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Amount.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedMonthlyBudget.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/SavingsGoalCard.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/tabs/AnalyticsTabPane.java
Labels: priority.medium :2nd_place_medal:, type.task :clipboard:

#287 Exclude UI from test coverage
  .github/check-trailing-whitespace.sh
  build.gradle
  config/travis/check-eof-newline.sh
  config/travis/check-line-endings.sh
  config/travis/check-trailing-whitespace.sh
  config/travis/run-checks.sh
Labels: priority.medium :2nd_place_medal:, type.testing :rescue_worker_helmet:

#285 Add empty argument error checks
  src/main/java/ay2021s1_cs2103_w16_3/finesse/commons/core/Messages.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/commons/util/StringUtil.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FindCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ParserUtil.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/category/Category.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Amount.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Date.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Title.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/commons/util/StringUtilTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/EditCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FindCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ParserUtilTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmark/EditBookmarkExpenseCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmark/EditBookmarkIncomeCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/TitleContainsKeyphrasesPredicateTest.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#294 Fix coding standard violation
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
Labels: priority.medium :2nd_place_medal:, type.task :clipboard:

#289 Ban time travel
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/Logic.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/LogicManager.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/time/Clock.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/time/SystemClock.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/time/Timekeeper.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/time/exceptions/TemporalException.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/CommandBox.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/DisabledWindow.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
  src/main/resources/images/sus.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DisabledWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/LogicManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/time/SystemClockTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/time/TimekeeperTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/time/exceptions/TemporalExceptionTest.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#288 Add switching of tabs when executing add and budget commands
  docs/UserGuide.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandResult.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/budget/SetExpenseLimitCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/budget/SetSavingsGoalCommand.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandTestUtil.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/budget/SetExpenseLimitCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/budget/SetSavingsGoalCommandTest.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#295 Add MonthlyBudget tests
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlyBudget.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Amount.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlyBudgetTest.java
Labels: priority.medium :2nd_place_medal:, type.testing :rescue_worker_helmet:

#296 Add Pitest as CI with artifact
  .github/workflows/gradle.yml
Labels: priority.low :3rd_place_medal:, type.task :clipboard:

#298 Add tests for CalculatedAmount
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/CalculatedAmountTest.java
Labels: priority.medium :2nd_place_medal:, type.testing :rescue_worker_helmet:

#301 Remove duplicate BookmarkTransactionBuilder
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/BookmarkTransactionBuilder.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/AddBookmarkExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/AddBookmarkIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/EditBookmarkExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/EditBookmarkIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmark/AddBookmarkExpenseCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmark/AddBookmarkIncomeCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/bookmark/BookmarkExpenseListTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/bookmark/BookmarkExpenseTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/bookmark/BookmarkIncomeListTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/bookmark/BookmarkIncomeTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/BookmarkTransactionBuilder.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TypicalTransactions.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#303 Increase code coverage for parsers
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ArgumentTokenizer.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/CliSyntax.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/Prefix.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/BookmarkTransactionBuilder.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/DeleteCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ParserUtilTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/PrefixTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmark/BookmarkTransactionBuilderTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/time/SystemClockTest.java
Labels: priority.medium :2nd_place_medal:, type.testing :rescue_worker_helmet:

#306 Set background colour of BorderPane
  src/main/resources/view/MainWindow.fxml
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#304 Rewrite MonthlyBudget calculations
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlyBudget.java
Labels: priority.medium :2nd_place_medal:, type.task :clipboard:

#309 Increase code coverage for commands
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandResultTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindTransactionCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/TabCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/AddBookmarkExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/AddBookmarkIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/ConvertBookmarkExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/ConvertBookmarkIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/EditBookmarkExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/EditBookmarkIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/EditBookmarkTransactionDescriptorTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/budget/SetExpenseLimitCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/budget/SetSavingsGoalCommandTest.java
Labels: priority.medium :2nd_place_medal:, type.testing :rescue_worker_helmet:

#299 Update developer guide for model, find feature and budget feature
  docs/Configuration.md
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Documentation.md
  docs/Logging.md
  docs/SettingUp.md
  docs/Testing.md
  docs/diagrams/BudgetActivityDiagram.puml
  docs/diagrams/BudgetClassDiagram.puml
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/FindClassDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SetExpenseLimitSequenceDiagram.puml
  docs/images/BudgetActivityDiagram.png
  docs/images/BudgetClassDiagram.png
  docs/images/FindActivityDiagram.png
  docs/images/FindClassDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/SetExpenseLimitSequenceDiagram.png
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#311 Add '+' and '-' signs to amounts displayed on Overview tab
  docs/UserGuide.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/SavingsGoalCard.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/TransactionCard.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/TransactionListPanel.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#308 Modify parsing of prefixes
  docs/UserGuide.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/commons/core/Messages.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ArgumentMultimap.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ArgumentTokenizer.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/CliSyntax.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/EditCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FindCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ParserUtil.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/TransactionBuilder.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/BookmarkTransactionBuilder.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/ConvertBookmarkCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/EditBookmarkCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/budgetparsers/SetExpenseLimitCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/budgetparsers/SetSavingsGoalCommandParser.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/LogicManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindTransactionCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListTransactionCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddExpenseCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddIncomeCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ArgumentTokenizerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ParserUtilTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/TransactionBuilderTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmark/AddBookmarkIncomeCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmark/ConvertBookmarkCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmark/EditBookmarkCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/TransactionListTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/HasCategoriesPredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/HasExactAmountPredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/InAmountRangePredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/InDateRangePredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/OnExactDatePredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/TitleContainsKeyphrasesPredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedExpenseTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedIncomeTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonFinanceTrackerStorageTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TypicalTransactions.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#313 Fix budget month order
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlyBudget.java
Labels: priority.high :1st_place_medal:, type.bug :bug:

#317 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/AnalyticsTabObjectDiagram.puml
  docs/images/AnalyticsTabObjectDiagram.png
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#314 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/AddTransactionActivityDiagram.puml
  docs/diagrams/AddTransactionClassDiagram.puml
  docs/diagrams/AddTransactionSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DeleteTransactionActivityDiagram.puml
  docs/diagrams/DeleteTransactionClassDiagram.puml
  docs/diagrams/EditTransactionActivityDiagram.puml
  docs/diagrams/EditTransactionClassDiagram.puml
  docs/diagrams/EditTransactionSequenceDiagram.puml
  docs/diagrams/EditTransactionSequenceDiagram2.puml
  docs/images/AddTransactionActivityDiagram.png
  docs/images/AddTransactionClassDiagram.png
  docs/images/AddTransactionSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteTransactionActivityDiagram.png
  docs/images/DeleteTransactionClassDiagram.png
  docs/images/EditTransactionActivityDiagram.png
  docs/images/EditTransactionClassDiagram.png
  docs/images/EditTransactionSequenceDiagram.png
  docs/images/EditTransactionSequenceDiagram2.png
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#318 Update developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommandHistoryClassDiagram.puml
  docs/diagrams/CommandHistoryDownActivityDiagram.puml
  docs/diagrams/CommandHistoryUpActivityDiagram.puml
  docs/diagrams/CommandResultSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/TimekeeperSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/CommandHistoryClassDiagram.png
  docs/images/CommandHistoryDownActivityDiagram.png
  docs/images/CommandHistoryUpActivityDiagram.png
  docs/images/CommandResultSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/TimekeeperSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#320 Update index page and README
  README.md
  docs/index.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#315 Update developer guide for bookmark transaction feature
  docs/DeveloperGuide.md
  docs/diagrams/ConvertBookmarkExpenseSequenceDiagram.puml
  docs/diagrams/bookmarkdiagrams/AddBookmarkExpenseSequenceDiagram.puml
  docs/diagrams/bookmarkdiagrams/AddBookmarkTransactionClassDiagram.puml
  docs/diagrams/bookmarkdiagrams/BookmarkTransactionClassDiagram.puml
  docs/diagrams/bookmarkdiagrams/BookmarkTransactionCommandClassDiagram.puml
  docs/diagrams/bookmarkdiagrams/ConvertBookmarkTransactionClassDiagram.puml
  docs/diagrams/bookmarkdiagrams/DeleteBookmarkExpenseActivityDiagram.puml
  docs/diagrams/bookmarkdiagrams/DeleteBookmarkTransactionClassDiagram.puml
  docs/diagrams/bookmarkdiagrams/EditBookmarkTransactionClassDiagram.puml
  docs/diagrams/bookmarkdiagrams/ParsingAddBookmarkExpenseInputSequenceDiagram.puml
  docs/diagrams/bookmarkdiagrams/ParsingConvertBookmarkExpenseInputSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/AddBookmarkExpenseSequenceDiagram.png
  docs/images/AddBookmarkTransactionClassDiagram.png
  docs/images/BookmarkTransactionClassDiagram.png
  docs/images/BookmarkTransactionCommandClassDiagram.png
  docs/images/ConvertBookmarkExpenseSequenceDiagram.png
  docs/images/ConvertBookmarkTransactionClassDiagram.png
  docs/images/DeleteBookmarkExpenseActivityDiagram.png
  docs/images/DeleteBookmarkTransactionClassDiagram.png
  docs/images/EditBookmarkTransactionClassDiagram.png
  docs/images/ParsingAddBookmarkExpenseInputSequenceDiagram.png
  docs/images/ParsingConvertBookmarkExpenseInputSequenceDiagram.png
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#322 Finalise user guide
  docs/UserGuide.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#321 Update PPP for Jingjing
  docs/team/zhaojj2209.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#323 Update PPP for Wei Liang
  docs/team/wltan.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#325 Update PPP for Yong Ping
  docs/team/yongping827.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#326 Finalise PPP for Ian
  docs/team/ianyong.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#324 Update screenshots for User Guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/userguide/AddExpense.png
  docs/images/userguide/AddIncome.png
  docs/images/userguide/EditExpense.png
  docs/images/userguide/EditIncome.png
  docs/images/userguide/OverviewTab.png
  docs/images/userguide/SetExpenseLimit.png
  docs/images/userguide/SetSavingsGoal.png
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#327 Update PPP
  docs/team/siddarth2824.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#328 Finalise developer guide
  docs/DeveloperGuide.md
  docs/images/DeleteBookmarkExpenseActivityDiagram.png
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#329 Edit user guide for CS2101 submission
  docs/UserGuide.md
Labels: type.documentation :roll_of_paper:

#330 Edit user guide for CS2101 submission
  docs/UserGuide.md
Labels: type.documentation :roll_of_paper:

#331 Edit user guide for CS2101 submission
  docs/UserGuide.md
  docs/images/userguide/AddExpense.png
  docs/images/userguide/AddIncome.png
  docs/images/userguide/AnalyticsTab.png
  docs/images/userguide/EditExpense.png
  docs/images/userguide/EditIncome.png
  docs/images/userguide/ExpensesTab.png
  docs/images/userguide/FindExpenses.png
  docs/images/userguide/FindIncomes.png
  docs/images/userguide/IncomesTab.png
  docs/images/userguide/UserGuide.png
  docs/images/userguide/bookmark/AnnotatedAddBookmarkExpense.png
  docs/images/userguide/bookmark/AnnotatedAddBookmarkIncome.png
  docs/images/userguide/bookmark/AnnotatedBookmarkExpenseOverview.png
  docs/images/userguide/bookmark/AnnotatedBookmarkIncomeOverview.png
  docs/images/userguide/bookmark/AnnotatedConvertBookmarkExpense.png
  docs/images/userguide/bookmark/AnnotatedConvertBookmarkIncome.png
  docs/images/userguide/bookmark/AnnotatedEditBookmarkExpense.png
  docs/images/userguide/bookmark/AnnotatedEditBookmarkIncome.png
Labels: type.documentation :roll_of_paper:
