Repository AY2021S1-CS2103T-W16-3/tp, pull requests merged in 2020-10, with the labels that each got.

#48 Remove 'address' field from 'person' model
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/transaction/Address.java
  src/main/java/seedu/address/model/transaction/Transaction.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTransaction.java
  src/main/java/seedu/address/ui/TransactionCard.java
  src/main/resources/view/TransactionListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditTransactionDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/transaction/AddressTest.java
  src/test/java/seedu/address/model/transaction/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/transaction/TransactionTest.java
  src/test/java/seedu/address/model/transaction/UniqueTransactionListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTransactionTest.java
  src/test/java/seedu/address/testutil/EditTransactionDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TransactionBuilder.java
  src/test/java/seedu/address/testutil/TransactionUtil.java
  src/test/java/seedu/address/testutil/TypicalTransactions.java
Labels: pr.ready-for-review :memo:, priority.medium :2nd_place_medal:, type.task :clipboard:

#49 Add additional menu to the menubar
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#50 Add skeleton classes for Expense and Income
  src/main/java/seedu/address/model/transaction/Expense.java
  src/main/java/seedu/address/model/transaction/Income.java
Labels: priority.medium :2nd_place_medal:, type.task :clipboard:

#51 Add 2020-10-02 minutes
  docs/minutes/20201002.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#58 Add Gantt chart to GitHub Pages
  docs/GanttChart.md
  docs/_config.yml
  docs/_layouts/chart.html
  docs/_layouts/widescreen.html
  docs/_sass/minima/_base.scss
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#56 Add income commands
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddressBookParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Income.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddIncomeCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddressBookParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TransactionBuilder.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TransactionUtil.java
Labels: priority.medium :2nd_place_medal:, type.story :books:

#66 Change 'category' prefix
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/CliSyntax.java
Labels: priority.medium :2nd_place_medal:, type.task :clipboard:

#65 Fix meeting minutes titles
  docs/_includes/head.html
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#72 Remove duplicate checks
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/FinanceTracker.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/Model.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManager.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ReadOnlyFinanceTracker.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Transaction.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/TransactionList.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/exceptions/DuplicateTransactionException.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonSerializableFinanceTracker.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddCommandIntegrationTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/FinanceTrackerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/TransactionListTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/TransactionTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/UniqueTransactionListTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonSerializableFinanceTrackerTest.java
Labels: priority.medium :2nd_place_medal:, type.task :clipboard:

#73 Rework model validation rules
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Amount.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Date.java
  src/test/data/JsonSerializableFinanceTrackerTest/duplicatePersonFinanceTracker.json
  src/test/data/JsonSerializableFinanceTrackerTest/typicalPersonsFinanceTracker.json
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandTestUtil.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ParserUtilTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/AmountTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/DateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/TitleContainsKeywordsPredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TransactionBuilder.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TypicalTransactions.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#74 Add meeting minutes for 6 October 2020
  docs/Gemfile
  docs/Gemfile.lock
  docs/minutes/20201006.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#75 Update UI to match project UI mockup
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/CommandBox.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/TransactionCard.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/TransactionListPanel.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/expense/ExpensePanel.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/income/IncomePanel.java
  src/main/resources/fonts/Eczar-Regular.ttf
  src/main/resources/fonts/RobotoCondensed-Regular.ttf
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ExpensePanel.fxml
  src/main/resources/view/IncomePanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/TransactionListCard.fxml
  src/main/resources/view/TransactionListPanel.fxml
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#76 Modify storage to handle expense and income
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/FinanceTracker.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ReadOnlyFinanceTracker.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/ExpenseList.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/IncomeList.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/util/SampleDataUtil.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedExpense.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedIncome.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonSerializableFinanceTracker.java
  src/test/data/JsonSerializableFinanceTrackerTest/invalidPersonFinanceTracker.json
  src/test/data/JsonSerializableFinanceTrackerTest/typicalPersonsFinanceTracker.json
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/FinanceTrackerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/ExpenseListTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/IncomeListTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedExpenseTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedIncomeTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TypicalTransactions.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#77 Modify Logic and Model to handle expense and income
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/Logic.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/LogicManager.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/Model.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManager.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/FinanceTrackerBuilder.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#79 Fix input validation for 'category'
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/category/Category.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandTestUtil.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ParserUtilTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedExpenseTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedIncomeTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedTransactionTest.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#85 Refactor IncomePanel and ExpensePanel to display incomes and expenses
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/expense/ExpensePanel.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/income/IncomePanel.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#83 Refactor logic to allow for UI-dependent behaviour
  src/main/java/ay2021s1_cs2103_w16_3/finesse/MainApp.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/Logic.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/LogicManager.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiManager.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiState.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/LogicManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/ui/UiStateTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#87 Add 2020-10-10 minutes
  docs/minutes/20201010.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#90 Add 'tab' command
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandResult.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/TabCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/TabCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiState.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandResultTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/TabCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/TabCommandParserTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#93 Modify 'delete' command to depend on UI state
  src/main/java/ay2021s1_cs2103_w16_3/finesse/commons/core/Messages.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/LogicManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#96 Remove unused messages from delete commands
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteIncomeCommand.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#97 Modify user guide link in help window
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/HelpWindow.java
Labels: priority.medium :2nd_place_medal:, type.story :books:

#94 Modify 'find' command to depend on UI state
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindTransactionCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#102 Fix list commands
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Expense.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Income.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListTransactionCommandTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#103 Modify TypicalTransactions.getTypicalFinanceTracker
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TypicalTransactions.java
Labels: priority.low :3rd_place_medal:, type.task :clipboard:

#105 Remove trailing whitespace from minutes 2020-10-10
  docs/minutes/20201010.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#106 Modify 'add' command to depend on UI state
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/LogicManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#101 Update UI styling to match UI mockup
  src/main/java/ay2021s1_cs2103_w16_3/finesse/commons/core/GuiSettings.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/CommandBox.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/HelpWindow.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/SavingsGoalPanel.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/TransactionCard.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiManager.java
  src/main/resources/images/SavingsImage.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/SavingsGoalPanel.fxml
  src/main/resources/view/TransactionListCard.fxml
  src/main/resources/view/TransactionListPanel.fxml
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#107 Modify 'edit' command to depend on UI state
  src/main/java/ay2021s1_cs2103_w16_3/finesse/commons/core/Messages.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/FinanceTracker.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManager.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandTestUtil.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#109 Fix error while loading custom fonts
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiManager.java
  src/main/resources/view/DarkTheme.css
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#113 Fix 'tab' command not working with TabPane
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiState.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/ui/UiStateTest.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#118 Add meeting minutes for 16 October 2020
  docs/minutes/20201016.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#122 Use LocalDate for Date model and add validation
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Date.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedExpense.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedIncome.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedTransaction.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandTestUtil.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/DateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TransactionUtil.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#123 Modify implementation of transaction, expense and income lists
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/FinanceTracker.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/Model.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManager.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Date.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Expense.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Income.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Title.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Transaction.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/TransactionList.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonSerializableFinanceTracker.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandTestUtil.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindTransactionCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ListTransactionCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonFinanceTrackerStorageTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/FinanceTrackerBuilder.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TypicalTransactions.java
Labels: priority.medium :2nd_place_medal:, type.task :clipboard:

#124 Use BigDecimal for Amount model
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Amount.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedExpense.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedIncome.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedTransaction.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/TransactionCard.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/AmountTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TransactionUtil.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#127 Delete ExpenseList, IncomeList and JsonAdaptedTransaction
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/ExpenseList.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/IncomeList.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedTransaction.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/ExpenseListTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/IncomeListTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedTransactionTest.java
Labels: priority.medium :2nd_place_medal:, type.task :clipboard:

#114 Update user guide
  docs/UserGuide.md
  docs/images/Ui.png
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#130 Update 'title' and 'category' validation
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/category/Category.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Title.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandTestUtil.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ParserUtilTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/category/CategoryTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/TitleTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedExpenseTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedIncomeTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#132 Add tests to increase code coverage for 'model' components
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/util/SampleDataUtil.java
  src/test/data/JsonFinanceTrackerStorageTest/invalidAndValidPersonFinanceTracker.json
  src/test/data/JsonFinanceTrackerStorageTest/invalidAndValidTransactionsFinanceTracker.json
  src/test/data/JsonFinanceTrackerStorageTest/invalidPersonFinanceTracker.json
  src/test/data/JsonFinanceTrackerStorageTest/invalidTransactionsFinanceTracker.json
  src/test/data/JsonSerializableFinanceTrackerTest/duplicatePersonFinanceTracker.json
  src/test/data/JsonSerializableFinanceTrackerTest/duplicateTransactionsFinanceTracker.json
  src/test/data/JsonSerializableFinanceTrackerTest/invalidPersonFinanceTracker.json
  src/test/data/JsonSerializableFinanceTrackerTest/invalidTransactionsFinanceTracker.json
  src/test/data/JsonSerializableFinanceTrackerTest/typicalPersonsFinanceTracker.json
  src/test/data/JsonSerializableFinanceTrackerTest/typicalTransactionsFinanceTracker.json
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/LogicManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandTestUtil.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditTransactionDescriptorTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindTransactionCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddExpenseCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddIncomeCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/EditCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FindCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/FinanceTrackerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/UserPrefsTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/AmountTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/DateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/TitleContainsKeywordsPredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/TransactionListTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/TransactionTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/util/SampleDataUtilTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedExpenseTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedIncomeTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonFinanceTrackerStorageTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonSerializableFinanceTrackerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TransactionBuilder.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TypicalTransactions.java
Labels: priority.medium :2nd_place_medal:, type.testing :rescue_worker_helmet:

#134 Enable assertions
  build.gradle
Labels: priority.medium :2nd_place_medal:, type.task :clipboard:

#135 Make Transaction abstract
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/Model.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManager.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Transaction.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/LogicManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddCommandIntegrationTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/TitleContainsKeywordsPredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/TransactionListTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/TransactionTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TransactionBuilder.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TransactionUtil.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TypicalTransactions.java
Labels: priority.medium :2nd_place_medal:, type.task :clipboard:

#138 Fix jarfile name
  build.gradle
  docs/UserGuide.md
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#140 Update Developer guide and DevOps guide
  docs/DevOps.md
  docs/DeveloperGuide.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Amount.java
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#141 Add implementation details of programmatic tab switching to Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/CommandResultSequenceDiagram.puml
  docs/images/CommandResultSequenceDiagram.png
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#142 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ConvertFrequentExpenseSequenceDiagram.puml
  docs/images/ConvertFrequentExpenseSequenceDiagram.png
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/DeleteCommandParser.java
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#143 Update Model and Storage sections in Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#144 Minor fixes to developer guide
  docs/DeveloperGuide.md
  docs/images/FindSequenceDiagram.png
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#152 Update trailing whitespace check
  config/travis/check-trailing-whitespace.sh
  docs/DeveloperGuide.md
Labels: priority.low :3rd_place_medal:, type.task :clipboard:

#150 Set monthly expense limit
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/Logic.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/LogicManager.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/budget/SetExpenseLimitCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/budgetparsers/SetExpenseLimitCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/FinanceTracker.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/Model.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManager.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ReadOnlyFinanceTracker.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlyBudget.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlyExpenseLimit.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/ObservableAmount.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedMonthlyBudget.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonSerializableFinanceTracker.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/SavingsGoalPanel.java
  src/test/data/JsonSerializableFinanceTrackerTest/typicalTransactionsFinanceTracker.json
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/frequentcommands/AddFrequentExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/frequentcommands/AddFrequentIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlyExpenseLimitTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedMonthlyBudgetTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/MonthlyBudgetBuilder.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#161 Refactor tabs
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/TransactionListPanel.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiManager.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiState.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/tabs/AnalyticsTabPane.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/tabs/ExpenseTabPane.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/tabs/IncomeTabPane.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/tabs/OverviewTabPane.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/tabs/TwoColumnTabPane.java
  src/main/resources/view/AnalyticsTabPane.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TwoColumnTabPane.fxml
  src/test/java/ay2021s1_cs2103_w16_3/finesse/ui/UiStateTest.java
Labels: priority.medium :2nd_place_medal:, type.task :clipboard:

#163 Add 2020-10-23 minutes
  docs/minutes/20201023.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#168 Fix expense and income lists to update automatically
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManager.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManagerTest.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#173 Standardize parse exception precedence across commands
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#169 Update layout of user guide
  docs/UserGuide.md
Labels: priority.low :3rd_place_medal:, type.documentation :roll_of_paper:

#172 Add calculations of budget and savings
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/Logic.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/LogicManager.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ClearCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandResult.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ExitCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/HelpCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/budget/SetExpenseLimitCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/budget/SetSavingsGoalCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/frequent/ConvertFrequentExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/frequent/ConvertFrequentIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/FinanceTracker.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/Model.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManager.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlyBudget.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlyExpenseLimit.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlySavingsGoal.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/ObservableAmount.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Amount.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Date.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Transaction.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonSerializableFinanceTracker.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/SavingsGoalPanel.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/tabs/AnalyticsTabPane.java
  src/main/resources/view/SavingsGoalPanel.fxml
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ClearCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandResultTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandTestUtil.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/DeleteIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/EditIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/ExitCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/HelpCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/budget/SetExpenseLimitCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/budget/SetSavingsGoalCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/frequentcommands/AddFrequentExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/frequentcommands/AddFrequentIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/frequentcommands/ConvertFrequentExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/frequentcommands/ConvertFrequentIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/stubs/EditCommandStub.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlyExpenseLimitTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlySavingsGoalTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedMonthlyBudgetTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#174 Make UI resizable
  src/main/java/ay2021s1_cs2103_w16_3/finesse/commons/core/GuiSettings.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlyBudget.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiManager.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ExpensePanel.fxml
  src/main/resources/view/FrequentTransactionPanel.fxml
  src/main/resources/view/IncomePanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/SavingsGoalPanel.fxml
  src/main/resources/view/TransactionListCard.fxml
  src/main/resources/view/TwoColumnTabPane.fxml
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/LogicManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/UserPrefsTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonUserPrefsStorageTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/storage/StorageManagerTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#176 Partially update user guide
  docs/UserGuide.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#178 Partially update user guide
  docs/UserGuide.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#179 Partially update user guide
  docs/UserGuide.md
  docs/_config.yml
  docs/_sass/minima/_layout.scss
  docs/images/userguide/AnalyticsTab.png
  docs/images/userguide/ExpensesTab.png
  docs/images/userguide/IncomesTab.png
  docs/images/userguide/OverviewTab.png
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#180 Partially update user guide
  docs/UserGuide.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#181 Partially update user guide
  docs/UserGuide.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#177 Add content to Analytics tab
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/tabs/AnalyticsTabPane.java
  src/main/resources/view/AnalyticsTabPane.fxml
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#183 Refactor add command for frequent expense and frequent income
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/frequent/AddFrequentExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/frequent/AddFrequentIncomeCommand.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#188 Refactor Ui to display dates of transactions
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/TransactionCard.java
  src/main/resources/view/TransactionListCard.fxml
Labels: priority.low :3rd_place_medal:, type.enhancement :+1:

#190 Fix CSS for ordered lists
  docs/_sass/minima/_layout.scss
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#194 Expand find command functionality
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindTransactionCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ArgumentMultimap.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/CliSyntax.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FindCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/AddBookmarkExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/AddBookmarkIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/ConvertBookmarkExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/ConvertBookmarkIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/Model.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManager.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/category/Category.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Amount.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Transaction.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/HasCategoriesPredicate.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/HasExactAmountPredicate.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/InAmountRangePredicate.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/InDateRangePredicate.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/OnExactDatePredicate.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/TitleContainsKeywordsPredicate.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/FindTransactionCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/AddBookmarkExpenseCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmarkcommands/AddBookmarkIncomeCommandTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/stubs/FindCommandStub.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/stubs/ModelStub.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FindCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/HasCategoriesPredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/HasExactAmountPredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/InAmountRangePredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/InDateRangePredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/OnExactDatePredicateTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/TitleContainsKeywordsPredicateTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#198 Add 'No External Site' page
  docs/NoExternalSite.html
  docs/_sass/minima/_layout.scss
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#197 Add amount prefix to set expense limit/savings goal commands
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/budgetparsers/SetExpenseLimitCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/budgetparsers/SetSavingsGoalCommandParser.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/budget/SetExpenseLimitCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/budget/SetSavingsGoalCommandParserTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#196 Restrict users from using certain commands for Bookmark Transactions
  docs/UserGuide.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmark/ConvertBookmarkCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmark/ConvertBookmarkExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmark/ConvertBookmarkIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmark/DeleteBookmarkCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmark/DeleteBookmarkExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmark/DeleteBookmarkIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmark/EditBookmarkCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmark/EditBookmarkExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmark/EditBookmarkIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FinanceTrackerParser.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#201 Add restrictions to command inputs
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ArgumentMultimap.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/FindCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/budgetparsers/SetExpenseLimitCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/budgetparsers/SetSavingsGoalCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Amount.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Transaction.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddExpenseCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddIncomeCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/budget/SetExpenseLimitCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/budget/SetSavingsGoalCommandParserTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#199 Add user guide to application
  build.gradle
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiState.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/tabs/UserGuideTabPane.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/UserGuideTabPane.fxml
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#203 Add application icon and website favicon
  docs/_includes/custom-head.html
  docs/assets/favicon.png
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/UiManager.java
Labels: priority.low :3rd_place_medal:, type.task :clipboard:

#205 Use relative URL for favicon path
  docs/_includes/custom-head.html
Labels: priority.low :3rd_place_medal:, type.bug :bug:

#206 Fix user guide bugs
  docs/UserGuide.md
  docs/index.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#209 Change instructions for set commands
  docs/UserGuide.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/budget/SetExpenseLimitCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/budget/SetSavingsGoalCommand.java
Labels: priority.high :1st_place_medal:, type.bug :bug:

#212 Load macOS default system font using its internal name
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/tabs/UserGuideTabPane.java
  src/main/resources/view/WebView.css
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#215 Fix crash when window coordinates is null
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
Labels: priority.high :1st_place_medal:, type.bug :bug:

#213 Make model data attributes private
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/category/Category.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Title.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/predicates/TitleContainsKeywordsPredicate.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedBookmarkExpense.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedBookmarkIncome.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedCategory.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedExpense.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/storage/JsonAdaptedIncome.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/TransactionCard.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/bookmark/BookmarkTransactionCard.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/CommandTestUtil.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManagerTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/testutil/TransactionUtil.java
Labels: priority.medium :2nd_place_medal:, type.task :clipboard:

#211 Refactor parsing logic to make date input optional
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/AddIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmark/ConvertBookmarkExpenseCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/commands/bookmark/ConvertBookmarkIncomeCommand.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/ConvertBookmarkExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/ConvertBookmarkIncomeCommandParser.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddExpenseCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddIncomeCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmark/ConvertBookmarkExpenseCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmark/ConvertBookmarkIncomeCommandParserTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#219 Fix transaction list to update on clear command
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManager.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/ModelManagerTest.java
Labels: priority.high :1st_place_medal:, type.bug :bug:

#207 Modify savings goal panel
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlyBudget.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Amount.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/SavingsGoalCard.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/SavingsGoalPanel.java
  src/main/resources/view/SavingsGoalCard.fxml
  src/main/resources/view/SavingsGoalPanel.fxml
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#217 Add duplicate restrictions to edit transaction and add bookmark commands
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/EditCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/AddBookmarkExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/AddBookmarkIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/EditBookmarkExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/EditBookmarkIncomeCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/bookmark/BookmarkTransaction.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddExpenseCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/AddIncomeCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/EditCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmark/AddBookmarkExpenseCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmark/AddBookmarkIncomeCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmark/EditBookmarkExpenseCommandParserTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmark/EditBookmarkIncomeCommandParserTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#224 Update User Guide
  docs/UserGuide.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#225 Fix analytics charts to update with the transaction list
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/budget/MonthlyBudget.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/tabs/AnalyticsTabPane.java
Labels: priority.high :1st_place_medal:, type.bug :bug:

#231 Disable scrolling of tabs using arrow keys
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/MainWindow.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#228 Modify duplicate check in bookmark expenses and incomes lists
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/bookmark/BookmarkExpense.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/bookmark/BookmarkExpenseList.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/bookmark/BookmarkIncome.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/bookmark/BookmarkIncomeList.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#232 Update user guide
  docs/UserGuide.md
Labels: priority.high :1st_place_medal:, type.documentation :roll_of_paper:

#234 Limit Amount to 8 digits
  docs/UserGuide.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Amount.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/AmountTest.java
Labels: priority.high :1st_place_medal:, type.bug :bug:

#235 Update user guide screenshots
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/userguide/AnalyticsTab.png
  docs/images/userguide/ExpensesTab.png
  docs/images/userguide/IncomesTab.png
  docs/images/userguide/OverviewTab.png
  docs/images/userguide/UserGuide.png
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#253 Add command history
  docs/UserGuide.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/command/history/CommandHistory.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/command/history/EvictingStack.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/command/history/Node.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/CommandBox.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/command/history/CommandHistoryTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/command/history/EvictingStackTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/command/history/NodeTest.java
Labels: priority.low :3rd_place_medal:, type.enhancement :+1:

#252 Add screenshots for bookmark commands
  docs/UserGuide.md
  docs/images/userguide/bookmark/AnnotatedAddBookmarkExpense.png
  docs/images/userguide/bookmark/AnnotatedAddBookmarkIncome.png
  docs/images/userguide/bookmark/AnnotatedBookmarkExpenseOverview.png
  docs/images/userguide/bookmark/AnnotatedBookmarkIncomeOverview.png
  docs/images/userguide/bookmark/AnnotatedConvertBookmarkExpense.png
  docs/images/userguide/bookmark/AnnotatedConvertBookmarkIncome.png
  docs/images/userguide/bookmark/AnnotatedEditBookmarkExpense.png
  docs/images/userguide/bookmark/AnnotatedEditBookmarkIncome.png
Labels: priority.low :3rd_place_medal:, type.documentation :roll_of_paper:

#257 Explicitly list out printable ASCII characters
  docs/UserGuide.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/category/Category.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Title.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/category/CategoryTest.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/TitleTest.java
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#254 Add additional parser method for parsing title
  docs/UserGuide.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ParserUtil.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/AddBookmarkExpenseCommandParser.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/bookmarkparsers/AddBookmarkIncomeCommandParser.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/logic/parser/ParserUtilTest.java
Labels: priority.medium :2nd_place_medal:, type.enhancement :+1:

#260 Fix inaccurate date validation
  docs/UserGuide.md
  src/main/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/Date.java
  src/test/java/ay2021s1_cs2103_w16_3/finesse/model/transaction/DateTest.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#258 Update user guide
  docs/UserGuide.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#261 Fix categories ScrollPane consuming all ScrollEvents
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/TransactionCard.java
  src/main/java/ay2021s1_cs2103_w16_3/finesse/ui/bookmark/BookmarkTransactionCard.java
Labels: priority.medium :2nd_place_medal:, type.bug :bug:

#263 Add image caption style
  docs/UserGuide.md
  docs/_sass/minima/_layout.scss
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#264 Add meeting minutes for 31 October 2020
  docs/minutes/20201031.md
Labels: priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:
