Repository AY2021S1-CS2103T-W16-3/tp, pull requests merged in 2020-09, with the labels that each got.

#3 Update Gradle to 6.6.1
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: pr::ready-to-merge :white_check_mark:, priority::medium :2nd_place_medal:, type::task 👉

#6 Add PIT mutation testing
  build.gradle
Labels: pr.ready-for-review :memo:, priority.medium :2nd_place_medal:, type.task :clipboard:

#10 Update 'About Us' information for Ian
  docs/AboutUs.md
  docs/images/ianyong.png
  docs/team/ianyong.md
Labels: pr.ready-to-merge :white_check_mark:, priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#11 Update 'About Us' information for Wei Liang
  docs/AboutUs.md
  docs/images/wltan.png
  docs/team/wltan.md
Labels: pr.ready-to-merge :white_check_mark:, priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#7 Add Git pre-push hook
  build.gradle
Labels: pr.ready-for-review :memo:, priority.medium :2nd_place_medal:, type.task :clipboard:

#12 Update 'About Us' information for Siddarth
  docs/AboutUs.md
  docs/images/siddarth2824.png
  docs/team/siddarth2824.md
Labels: pr.ready-to-merge :white_check_mark:, priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#15 Update information for Jingjing
  docs/AboutUs.md
  docs/images/zhaojj2209.png
  docs/team/zhaojj2209.md
Labels: pr.ready-to-merge :white_check_mark:, priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#16 Update 'About Us' information for Yong Ping
  docs/AboutUs.md
  docs/images/johndoe.png
  docs/images/yongping827.png
  docs/team/johndoe.md
  docs/team/yongping827.md
Labels: pr.ready-to-merge :white_check_mark:, priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#14 Update Developer Guide: NFR, Glossary
  docs/DeveloperGuide.md
Labels: pr.ready-for-review :memo:, priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#18 Add meeting minutes to GitHub Pages
  .github/workflows/build-jekyll.yml
  .gitignore
  docs/DeveloperGuide.md
  docs/Gemfile
  docs/Gemfile.lock
  docs/Minutes.md
  docs/_config.yml
  docs/_layouts/minutes.html
  docs/minutes/20200829.md
  docs/minutes/20200905.md
  docs/minutes/20200912.md
  docs/minutes/20200919.md
Labels: pr.ready-to-merge :white_check_mark:, priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:, type.enhancement :+1:

#23 Achieve parity between pre-push hook and CI job
  .github/check-eof-newline.sh
  .github/check-line-endings.sh
  .github/check-trailing-whitespace.sh
  .github/run-checks.sh
  build.gradle
Labels: pr.ready-to-merge :white_check_mark:, priority.medium :2nd_place_medal:, type.task :clipboard:

#36 Add 2020-09-25 minutes
  docs/minutes/20200925.md
Labels: pr.ready-to-merge :white_check_mark:, priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:

#29 Update README
  README.md
  docs/images/Ui.png
  docs/index.md
Labels: pr.ready-for-review :memo:, priority.medium :2nd_place_medal:, type.documentation :roll_of_paper:
